'use strict';
const KEY='suilven-web-v1', app=document.querySelector('#app');
const seed={version:1,jobs:[],parts:[{id:'oil',name:'Main engine oil filter',number:'RE504836',quantity:null,location:'',minimum:1}],service:{lastHours:2979,lastDate:'2026-02-27',interval:250},completions:[],passages:[],checks:[],manuals:[]};
let state,blocked=false,page='home';
try{state=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(seed);validate(state)}catch(e){state=structuredClone(seed);blocked=true}
function validate(s){if(s.version!==1||!['jobs','parts','completions','passages','checks','manuals'].every(k=>Array.isArray(s[k]))||!s.service||!Number.isFinite(s.service.lastHours)||s.service.interval<=0)throw Error('Unrecognised backup');for(const p of s.parts)if(p.quantity!==null&&(!Number.isFinite(p.quantity)||p.quantity<0))throw Error('Invalid stock')}
function commit(fn){if(blocked)throw Error('Existing records could not be read. Export recovery data before restoring a valid backup.');const next=structuredClone(state);fn(next);validate(next);localStorage.setItem(KEY,JSON.stringify(next));state=next}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function msg(t){document.querySelector('#message').textContent=t}
function field(name,label,type='text',value=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${type==='number'?'step="any" min="0"':''} required></label>`}
function download(name,content,type='application/json'){const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),10000)}
function num(f,k){const n=Number(f.get(k));if(f.get(k)===''||!Number.isFinite(n)||n<0)throw Error('Enter valid non-negative numbers');return n}
function render(){msg('');if(page==='home'){app.innerHTML=`<h1>Your boat. Everything in reach.</h1><p class="muted">Offline-first development build. Main engine: 3,139.7 h · Generator: 3,247.9 h. Reading dates unconfirmed.</p>${blocked?'<p class="warning">Storage could not be read. Saving is blocked to protect the original.</p>':''}<div class="grid">${[['service','Servicing'],['parts','Parts & Spares'],['jobs','Problems & Jobs'],['fuel','Passages & Fuel'],['checks','Pre-departure Checks'],['manuals','Manuals & Boat Information'],['backup','Backup & Restore']].map(([id,n])=>`<button class="tile" data-page="${id}">${n}</button>`).join('')}</div><p class="warning">Starter build: full manual schedules and historical inventory are still awaiting import and verification.</p>`}
if(page==='jobs'){app.innerHTML=`<h1>Problems & Jobs</h1><form id="job">${field('title','Problem or job')}<label>Notes<textarea name="notes"></textarea></label><label>Equipment<select name="equipment">${['Main engine','Wing engine','Generator','Other equipment'].map(e=>`<option>${e}</option>`).join('')}</select></label><button class="primary">Add job</button></form>${state.jobs.map(j=>`<article><h2>${esc(j.title)}</h2><p>${esc(j.notes)}</p><p class="muted">${esc(j.equipment)} · ${esc(j.date)}</p><button data-status="${j.id}">${esc(j.status)} — change status</button></article>`).join('')}`}
if(page==='parts'){app.innerHTML=`<h1>Parts & Spares</h1><p>Only the main oil filter is seeded. Historical quantities and box locations have not been treated as current stock.</p>${state.parts.map(p=>`<form id="stock"><h2>${esc(p.name)}</h2><p>${esc(p.number)}</p>${field('quantity','Counted quantity onboard','number',p.quantity??'')}${field('location','Current storage location','text',p.location)}${field('minimum','Reorder when stock reaches','number',p.minimum)}<button class="primary">Confirm stock</button>${p.quantity!==null&&p.quantity<=p.minimum?'<p class="warning">Reorder: at or below minimum stock.</p>':''}</form>`).join('')}`}
if(page==='service'){const t=state.service;app.innerHTML=`<h1>Servicing</h1><div class="grid"><button data-page="main" class="tile">Main engine</button><button data-pending class="tile">Wing engine</button><button data-pending class="tile">Generator</button><button data-pending class="tile">Other equipment</button></div><p>Other equipment schedules will be added after manual review.</p>`}
if(page==='main'){const t=state.service;app.innerHTML=`<h1>Main engine · Oil & filter</h1><section><p>Last recorded: ${t.lastHours} hours · ${esc(t.lastDate)}</p><h2>Next due: ${t.lastHours+t.interval} hours</h2><p>Owner interval: 250 hours. Oil: John Deere Plus 50, 15W-40. Calendar interval awaiting confirmation.</p></section><form id="service">${field('date','Completion date','date',new Date().toISOString().slice(0,10))}${field('hours','Engine hours','number')}${field('used','Oil filters actually used','number',1)}<label>Work notes<textarea name="notes"></textarea></label><button class="primary">Save service & deduct stock</button></form>${state.completions.slice().reverse().map(c=>`<article>${esc(c.date)} · ${c.hours} h · ${c.used} filter(s)<p>${esc(c.notes)}</p>${c.reversed?'Reversed':'<button data-undo="'+c.id+'">Undo completion</button>'}</article>`).join('')}`}
if(page==='fuel'){app.innerHTML=`<h1>Passages & Fuel</h1><p>Main tanks supply the main engine and generator. Wing engine tank is separate. Quantities below are total US gallons across the main tanks.</p><form id="fuel">${field('name','Passage name')}${['start','end','added','distance','duration'].map((k,i)=>field(k,['Starting fuel · US gal','Finishing fuel · US gal','Fuel added · US gal','Distance · NM','Duration · hours'][i],'number',k==='added'?0:'')).join('')}<button class="primary">Calculate & save</button></form>${state.passages.slice().reverse().map(p=>`<article><h2>${esc(p.name)}</h2><p>${p.litres.toFixed(1)} litres total used · ${(p.litres/p.duration).toFixed(2)} L/h · ${(p.litres/p.distance).toFixed(2)} L/NM</p><p>Average speed ${(p.distance/p.duration).toFixed(1)} knots. Combined main engine + generator consumption.</p></article>`).join('')}`}
if(page==='checks'){app.innerHTML=`<h1>Pre-departure Checks</h1><p class="warning">Starter checklist. Review against the boat manual before use.</p><button id="fresh">Start a fresh checklist</button>${state.checks.length?`<section><p>${esc(state.checks.at(-1).date)}</p>${state.checks.at(-1).items.map((c,i)=>`<label>${esc(c.title)}<select data-check="${i}">${['Unchecked','Checked','Needs attention','Not applicable'].map(v=>`<option ${c.status===v?'selected':''}>${v}</option>`).join('')}</select></label>`).join('')}</section>`:''}<p>${state.checks.length} dated checklists retained.</p>`}
if(page==='manuals'){app.innerHTML=`<h1>Manuals & Boat Information</h1><section><h2>Suilven · Nordhavn N43</h2><p>Hull N4334 · 2008. Main engine Lugger; exact nameplate model and equipment variants await confirmation.</p><p>Manual import, local document storage and page references are the next development stage. No private manuals have been uploaded to this website.</p></section>`}
if(page==='backup'){app.innerHTML=`<h1>Backup & Restore</h1><section><p>Export saves your local records as a JSON file. Keep it in Files on your iPad. Restore replaces this browser's current records after confirmation.</p><button id="export">Export backup</button><label>Restore a backup<input id="restore" type="file" accept=".json,application/json"></label><p>Native Swift backups and browser backups use different formats. This build does not import Swift records.</p></section>`}
}
document.querySelector('#home').onclick=()=>{page='home';render()};
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.page){page=b.dataset.page;render()}if(b.hasAttribute('data-pending'))msg('Schedule pending manual review');if(b.dataset.status){commit(s=>{const j=s.jobs.find(j=>j.id===b.dataset.status);j.status=({'Open':'In progress','In progress':'Completed','Completed':'Open'})[j.status]});render()}if(b.id==='fresh'){commit(s=>s.checks.push({date:new Date().toISOString(),items:['Engine oil and coolant','Leaks, belts and strainers','Seacock positions','Main and wing fuel','Shore power disconnected','Weather, tides and passage plan','Radios and navigation equipment','Crew briefing and safety equipment','Tender, hatches and loose gear'].map(title=>({title,status:'Unchecked'}))}));render()}if(b.id==='export')download('Suilven-backup.json',blocked?(localStorage.getItem(KEY)||''):JSON.stringify(state,null,2));if(b.dataset.undo){commit(s=>{const c=s.completions.find(c=>c.id===b.dataset.undo);if(c.reversed||s.completions.filter(c=>!c.reversed).at(-1)?.id!==c.id)throw Error('Undo the latest completion first');s.parts[0].quantity+=c.used;s.service=c.previous;c.reversed=true});render()}}catch(x){msg(x.message)}});
app.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);try{if(e.target.id==='job'){const title=f.get('title').trim();if(!title)throw Error('Enter a title');commit(s=>s.jobs.push({id:crypto.randomUUID(),title,notes:f.get('notes'),equipment:f.get('equipment'),status:'Open',date:new Date().toISOString().slice(0,10)}))}if(e.target.id==='stock')commit(s=>{s.parts[0].quantity=num(f,'quantity');s.parts[0].minimum=num(f,'minimum');s.parts[0].location=f.get('location').trim();if(!s.parts[0].location)throw Error('Enter a location')});if(e.target.id==='service'){const hours=num(f,'hours'),used=num(f,'used'),date=f.get('date');if(!Number.isInteger(used))throw Error('Filters used must be a whole number');if(date>new Date().toISOString().slice(0,10))throw Error('Completion cannot be in the future');commit(s=>{if(hours<s.service.lastHours||date<s.service.lastDate)throw Error('Completion precedes the recorded baseline');if(used>0&&(s.parts[0].quantity===null||s.parts[0].quantity<used))throw Error('Confirm sufficient stock in Parts & Spares first');s.completions.push({id:crypto.randomUUID(),date,hours,used,notes:f.get('notes'),previous:structuredClone(s.service),reversed:false});if(used>0)s.parts[0].quantity-=used;s.service.lastHours=hours;s.service.lastDate=date})}if(e.target.id==='fuel'){const p={name:f.get('name'),start:num(f,'start'),end:num(f,'end'),added:num(f,'added'),distance:num(f,'distance'),duration:num(f,'duration')};p.litres=(p.start+p.added-p.end)*3.785411784;if(p.litres<0||p.distance<=0||p.duration<=0)throw Error('Check fuel amounts; distance and duration must be positive');commit(s=>s.passages.push(p))}render();msg('Saved on this device')}catch(x){msg(x.message)}});
app.addEventListener('change',async e=>{try{if(e.target.dataset.check!==undefined){commit(s=>s.checks.at(-1).items[Number(e.target.dataset.check)].status=e.target.value);msg('Checklist saved')}if(e.target.id==='restore'&&e.target.files[0]){const next=JSON.parse(await e.target.files[0].text());validate(next);if(confirm('Replace current records? Export a backup first if needed.')){localStorage.setItem(KEY,JSON.stringify(next));state=next;blocked=false;render();msg('Backup restored')}}}catch(x){msg(x.message)}});
function connection(){document.querySelector('#connection').textContent=navigator.onLine?'Online':'Offline'}window.addEventListener('online',connection);window.addEventListener('offline',connection);connection();render();
if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js').catch(()=>msg('Offline cache unavailable; keep a backup.'));
