'use strict';
const KEY='suilven-web-v1', app=document.querySelector('#app');
const seed={version:1,jobs:[],parts:[{id:'oil',name:'Main engine oil filter',number:'RE504836',quantity:null,location:'',minimum:1}],service:{lastHours:2979,lastDate:'2026-02-27',interval:250},completions:[],passages:[],checks:[],manuals:[]};
let state,blocked=false,page='home',selectedPart='oil',selectedTask='',search='',partsReturnPage='parts',partsScroll=0,partSaved=false;
try{state=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(seed);validate(state)}catch(e){state=structuredClone(seed);blocked=true}
function validate(s){if(s.version!==1||!['jobs','parts','completions','passages','checks','manuals'].every(k=>Array.isArray(s[k]))||!s.service||!Number.isFinite(s.service.lastHours)||s.service.interval<=0)throw Error('Unrecognised backup');for(const p of s.parts)if(p.quantity!==null&&(!Number.isFinite(p.quantity)||p.quantity<0))throw Error('Invalid stock')}
function migrate(d){d.tasks??=[];d.scheduleDrafts??=[];for(const p of d.parts){p.supplier??="";p.aliases??="";p.category??="Engine";p.verified??=p.quantity!==null}return d}
state=migrate(state);
function commit(fn){if(blocked)throw Error('Existing records could not be read. Export recovery data before restoring a valid backup.');const next=migrate(structuredClone(state));fn(next);validate(next);localStorage.setItem(KEY,JSON.stringify(next));state=next}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function msg(t){document.querySelector('#message').textContent=t;const feedback=document.querySelector('#stock-feedback');if(feedback){feedback.textContent=t;feedback.className=t?'save-confirmation':'';if(t)feedback.scrollIntoView({block:'nearest'})}}
function field(name,label,type='text',value=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${type==='number'?'step="any" min="0"':''} required></label>`}
function download(name,content,type='application/json'){const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),10000)}
function num(f,k){const n=Number(f.get(k));if(f.get(k)===''||!Number.isFinite(n)||n<0)throw Error('Enter valid non-negative numbers');return n}
function render(){msg('');if(page==='home'){app.innerHTML=`<h1>Your boat. Everything in reach.</h1><p class="muted">Offline-first development build. Main engine: 3,139.7 h · Generator: 3,247.9 h. Reading dates unconfirmed.</p>${blocked?'<p class="warning">Storage could not be read. Saving is blocked to protect the original.</p>':''}<div class="grid">${[['service','Servicing'],['parts','Parts & Spares'],['jobs','Problems & Jobs'],['fuel','Passages & Fuel'],['checks','Pre-departure Checks'],['manuals','Manuals & Boat Information'],['backup','Backup & Restore']].map(([id,n])=>`<button class="tile" data-page="${id}">${n}</button>`).join('')}</div><p class="warning">Historical inventory can now be imported locally. Full manual schedules still need review.</p>`}
if(page==='jobs'){app.innerHTML=`<h1>Problems & Jobs</h1><form id="job">${field('title','Problem or job')}<label>Notes<textarea name="notes"></textarea></label><label>Equipment<select name="equipment">${['Main engine','Wing engine','Generator','Other equipment'].map(e=>`<option>${e}</option>`).join('')}</select></label><button class="primary">Add job</button></form>${state.jobs.map(j=>`<article><h2>${esc(j.title)}</h2><p>${esc(j.notes)}</p><p class="muted">${esc(j.equipment)} · ${esc(j.date)}</p><button data-status="${j.id}">${esc(j.status)} — change status</button></article>`).join('')}`}
if(page==='parts'){const matches=state.parts.filter(p=>[p.name,p.number,p.aliases,p.category,p.location,p.historicalLocation].join(' ').toLowerCase().includes(search.toLowerCase()));app.innerHTML=`<h1>Parts & Spares</h1>${partSaved?'<p class="save-confirmation" role="status">✓ Part saved on this device.</p>':''}<div class="row"><button data-page="inventory-import">Import historical inventory</button><button data-newpart>Add a part</button><button data-page="reorder">Reorder list</button></div><label>Search name, part number, supplier alias or location<input id="part-search" value="${esc(search)}" placeholder="e.g. impeller, RE504836 or generator"></label><p>${state.parts.length} catalogue entries · ${state.parts.filter(p=>p.verified).length} counted and confirmed</p>${matches.map(p=>`<article><h2>${esc(p.name)}</h2><p>${esc(p.number)} · ${esc(p.category)}</p><p>${p.verified?`${p.quantity} onboard · ${esc(p.location)}`:'Current quantity and location need checking'}</p>${p.verified&&p.quantity<=p.minimum?'<p class="warning">Reorder — at or below threshold</p>':''}<button data-part="${esc(p.id)}">View / confirm stock</button></article>`).join('')}`}
if(page==='part'){const p=state.parts.find(p=>p.id===selectedPart);app.innerHTML=`<h1>Part details</h1><button type="button" data-partsback>← Back to spares list</button>${partSaved?'<p class="save-confirmation" role="status">✓ Changes saved on this device.</p>':''}<p id="stock-feedback" role="status"></p>${partReferences(p)}<form id="stock" novalidate>${field('name','Part name','text',p.name)}${field('number','Part number','text',p.number)}${field('category','Equipment / category','text',p.category)}<fieldset><legend>Used by equipment · select all that apply</legend>${equipmentNames.map(n=>`<label><input type="checkbox" name="equipmentGroups" value="${n}" ${partGroups(p).includes(n)?'checked':''}>${n}</label>`).join('')}</fieldset><p class="warning">Historical record: ${esc(p.historicalQuantity??'not recorded')} · ${esc(p.historicalLocation??'not recorded')}. Check against the part label; imported numbers are unverified.</p><p class="muted">${esc(p.source??'Owner-entered record')}</p>${field('quantity','Counted quantity onboard','number',p.quantity??'')}${field('location','Current storage location','text',p.location)}${field('minimum','Reorder when stock reaches','number',p.minimum)}<label>Supplier / last purchase<input name="supplier" value="${esc(p.supplier)}"></label><label>Alternative supplier part numbers / fit notes<textarea name="aliases">${esc(p.aliases)}</textarea></label><p>Alternative numbers are notes, not verified interchangeable parts.</p><button class="primary" name="action" value="return">Save & return to list</button><button name="action" value="stay">Save & stay here</button></form>`}
if(page==='inventory-import'){app.innerHTML=`<h1>Import your inventory</h1><section><p>Select the Suilven historical inventory JSON file supplied separately. It is read locally; nothing is uploaded to GitHub.</p><p>Existing matched part numbers keep their current stock and location. Separate historical entries stay separate; repeated import IDs are skipped. Every newly imported item starts with unconfirmed current stock.</p><input id="inventory-file" type="file" accept=".json,application/json"></section>`}
if(page==='reorder'){const parts=state.parts.filter(p=>p.verified&&p.quantity<=p.minimum);app.innerHTML=`<h1>Reorder list</h1>${parts.length?parts.map(p=>`<article><h2>${esc(p.name)}</h2><p>${esc(p.number)} · ${p.quantity} onboard · threshold ${p.minimum}</p><p>${esc(p.supplier)}</p><button data-part="${esc(p.id)}">View part</button></article>`).join(''):'<p>No confirmed parts are at or below their threshold.</p>'}<p>Uncounted inventory is excluded; check it before ordering.</p>`}
if(page==='schedule-import'){app.innerHTML=`<h1>Engine schedule library</h1><p>Import the supplied schedule file locally. Review each reference, interval and last-service baseline before activating it. Existing schedules and the confirmed main-engine oil record are preserved.</p><p>This first library covers core recurring service tasks. Daily checks, commissioning and specialist injector / pump requirements still need separate review.</p><input id="schedule-file" type="file" accept=".json,application/json"><p>${state.scheduleDrafts.filter(d=>!d.activated).length} schedules awaiting review</p>${state.scheduleDrafts.filter(d=>!d.activated).map(d=>`<article><h2>${esc(d.equipment)} · ${esc(d.name)}</h2><p>${esc(d.source)}</p><p>${esc(d.reviewNotes)}</p><button data-draft="${esc(d.id)}">Review & activate</button></article>`).join('')}`}
if(page==='schedule-review'){const d=state.scheduleDrafts.find(d=>d.id===selectedTask);app.innerHTML=`<h1>${esc(d.equipment)} · ${esc(d.name)}</h1><p>${esc(d.source)}</p><p class="warning">${esc(d.reviewNotes)}</p><p>Suggested interval: ${d.intervalHours??'—'} hours / ${d.intervalMonths??'—'} months. ${esc(d.intervalBasis)}</p><p>Historical baseline: ${d.lastHours??'No meter recorded'} hours · ${esc(d.lastDate??'Date unknown')}. ${esc(d.baselineSource)}</p><form id="activate-schedule"><label>Chosen hour interval<input name="intervalHours" type="number" min="0" step="any" value="${d.intervalHours??''}"></label><label>Chosen month interval<input name="intervalMonths" type="number" min="0" step="1" value="${d.intervalMonths??''}"></label><label>Last completed hours<input name="lastHours" type="number" min="0" step="any" value="${d.lastHours??''}"></label><label>Last completed date<input name="lastDate" type="date" value="${esc(d.lastDate??'')}"></label>${field('basis','Reason for chosen interval / confirmation notes','text',d.intervalBasis)}${partPicker(d.equipment)}<p>Choose a part only after checking its fit. No supplier equivalents are assumed.</p><label><input name="confirmed" type="checkbox" required> I have checked applicability to the fitted equipment, the interval and the baseline.</label><button class="primary">Activate schedule</button></form>`}
if(page==='service'){const t=state.service;app.innerHTML=`<h1>Servicing</h1><button data-page="schedule-import">Import / review engine schedules</button><div class="grid"><button data-page="main" class="tile">Main engine</button><button data-equipment="Wing engine" class="tile">Wing engine</button><button data-equipment="Generator" class="tile">Generator</button><button data-equipment="Other equipment" class="tile">Other equipment</button></div><button data-equipment="Main engine">Additional main engine tasks</button><p>Add schedules using your verified manual or owner preference. Calendar and hour triggers use whichever comes first.</p>`}

if(page==='tasks'){app.innerHTML=`<h1>${esc(selectedTask)} · Servicing</h1><button data-page="newtask">Add a schedule</button>${state.tasks.filter(t=>t.equipment===selectedTask).map(t=>`<article><h2>${esc(t.name)}</h2><p>${esc(t.source)}</p><p>${t.lastHours!==null&&t.intervalHours?`Next at ${t.lastHours+t.intervalHours} hours`:'Hour baseline not set'} · ${t.lastDate&&t.intervalMonths?`Next date ${nextDate(t.lastDate,t.intervalMonths)}`:'Calendar baseline not set'}</p><button data-task="${t.id}">Record service</button></article>`).join('')}`}
if(page==='newtask'){app.innerHTML=`<h1>Add ${esc(selectedTask)} schedule</h1><form id="newtask">${field('name','Task name')}<label>Interval · engine hours (optional)<input name="intervalHours" type="number" step="any" min="0"></label><label>Interval · months (optional)<input name="intervalMonths" type="number" step="1" min="0"></label><label>Last completed engine hours (optional)<input name="lastHours" type="number" step="any" min="0"></label><label>Last completed date (optional)<input name="lastDate" type="date"></label>${field('source','Manual reference / owner preference')}${partPicker(selectedTask)}<button class="primary">Save schedule</button></form>`}
if(page==='task'){const t=state.tasks.find(t=>t.id===selectedTask);app.innerHTML=`<h1>${esc(t.name)}</h1><p>${esc(t.equipment)} · ${esc(t.source)}</p>${serviceReferences(t)}<form id="task-service">${field('date','Completed date','date',new Date().toISOString().slice(0,10))}<label>Equipment hours (optional)<input name="hours" type="number" step="any" min="0"></label>${field('used','Quantity used from linked part','number',t.part?1:0)}${partPicker(t.equipment,t.part)}<label>Work notes<textarea name="notes"></textarea></label><button class="primary">Record service & deduct stock</button></form>${state.completions.filter(c=>c.taskID===t.id).slice().reverse().map(c=>`<article>${esc(c.date)} · ${c.hours??'No meter'} hours<p>${esc(c.notes)}</p>${c.reversed?'Reversed':`<button data-taskundo="${c.id}">Undo completion</button>`}</article>`).join('')}`}

if(page==='main'){const t=state.service;app.innerHTML=`<h1>Main engine · Oil & filter</h1>${serviceReferences({equipment:'Main engine',name:'Oil and filter',importID:'main-oil'})}<section><p>Last recorded: ${t.lastHours} hours · ${esc(t.lastDate)}</p><h2>Next due: ${t.lastHours+t.interval} hours</h2><p>Owner interval: 250 hours. Oil: John Deere Plus 50, 15W-40. Calendar interval awaiting confirmation.</p></section><form id="service">${field('date','Completion date','date',new Date().toISOString().slice(0,10))}${field('hours','Engine hours','number')}${field('used','Oil filters actually used','number',1)}<label>Work notes<textarea name="notes"></textarea></label><button class="primary">Save service & deduct stock</button></form>${state.completions.filter(c=>!c.taskID).slice().reverse().map(c=>`<article>${esc(c.date)} · ${c.hours} h · ${c.used} filter(s)<p>${esc(c.notes)}</p>${c.reversed?'Reversed':'<button data-undo="'+c.id+'">Undo completion</button>'}</article>`).join('')}`}
if(page==='fuel'){app.innerHTML=`<h1>Passages & Fuel</h1><p>Main tanks supply the main engine and generator. Wing engine tank is separate. Quantities below are total US gallons across the main tanks.</p><form id="fuel">${field('name','Passage name')}${['start','end','added','distance','duration'].map((k,i)=>field(k,['Starting fuel · US gal','Finishing fuel · US gal','Fuel added · US gal','Distance · NM','Duration · hours'][i],'number',k==='added'?0:'')).join('')}<button class="primary">Calculate & save</button></form>${state.passages.slice().reverse().map(p=>`<article><h2>${esc(p.name)}</h2><p>${p.litres.toFixed(1)} litres total used · ${(p.litres/p.duration).toFixed(2)} L/h · ${(p.litres/p.distance).toFixed(2)} L/NM</p><p>Average speed ${(p.distance/p.duration).toFixed(1)} knots. Combined main engine + generator consumption.</p></article>`).join('')}`}
if(page==='checks'){app.innerHTML=`<h1>Pre-departure Checks</h1><p class="warning">Starter checklist. Review against the boat manual before use.</p><button id="fresh">Start a fresh checklist</button>${state.checks.length?`<section><p>${esc(state.checks.at(-1).date)}</p>${state.checks.at(-1).items.map((c,i)=>`<label>${esc(c.title)}<select data-check="${i}">${['Unchecked','Checked','Needs attention','Not applicable'].map(v=>`<option ${c.status===v?'selected':''}>${v}</option>`).join('')}</select></label>`).join('')}</section>`:''}<p>${state.checks.length} dated checklists retained.</p>`}
if(page==='manuals'){app.innerHTML=`<h1>Manuals & Boat Information</h1><p>PDF copies stay in this browser on this iPad. Keep originals in Files. JSON backups include catalogue entries only, not PDF files.</p><form id="manual-import"><label>Equipment<select name="equipment"><option>Automatic from filename</option>${equipmentNames.map(n=>`<option>${n}</option>`).join('')}</select></label><label>Select PDFs from Files<input name="files" type="file" accept=".pdf,application/pdf" multiple required></label><button class="primary">Save selected manuals offline</button></form><p id="manual-status" role="status"></p><button id="manual-storage">Check storage / request retention</button><p id="manual-storage-status"></p>${manualLibrary()}`}
if(page==='backup'){app.innerHTML=`<h1>Backup & Restore</h1><section><p>Export saves your local records as a JSON file. Keep it in Files on your iPad. Restore replaces this browser's current records after confirmation.</p><button id="export">Export backup</button><label>Restore a backup<input id="restore" type="file" accept=".json,application/json"></label><p>Native Swift backups and browser backups use different formats. This build does not import Swift records.</p></section>`}
}
document.querySelector('#home').onclick=()=>{page='home';render()};
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.page){page=b.dataset.page;render()}if(b.hasAttribute('data-pending'))msg('Schedule pending manual review');if(b.dataset.status){commit(s=>{const j=s.jobs.find(j=>j.id===b.dataset.status);j.status=({'Open':'In progress','In progress':'Completed','Completed':'Open'})[j.status]});render()}if(b.id==='fresh'){commit(s=>s.checks.push({date:new Date().toISOString(),items:['Engine oil and coolant','Leaks, belts and strainers','Seacock positions','Main and wing fuel','Shore power disconnected','Weather, tides and passage plan','Radios and navigation equipment','Crew briefing and safety equipment','Tender, hatches and loose gear'].map(title=>({title,status:'Unchecked'}))}));render()}if(b.id==='export')download('Suilven-backup.json',blocked?(localStorage.getItem(KEY)||''):JSON.stringify(state,null,2));if(b.dataset.undo){commit(s=>{const c=s.completions.find(c=>c.id===b.dataset.undo);if(c.reversed||s.completions.filter(c=>!c.reversed&&!c.taskID).at(-1)?.id!==c.id)throw Error('Undo the latest completion first');s.parts[0].quantity+=c.used;s.service=c.previous;c.reversed=true});render()}}catch(x){msg(x.message)}});
app.addEventListener('submit',e=>{e.preventDefault();if(!['job','stock','service','fuel'].includes(e.target.id))return;const f=new FormData(e.target);try{if(e.target.id==='job'){const title=f.get('title').trim();if(!title)throw Error('Enter a title');commit(s=>s.jobs.push({id:crypto.randomUUID(),title,notes:f.get('notes'),equipment:f.get('equipment'),status:'Open',date:new Date().toISOString().slice(0,10)}))}if(e.target.id==='stock')commit(s=>{const p=s.parts.find(p=>p.id===selectedPart);p.quantity=optionalNum(f,'quantity');p.minimum=num(f,'minimum');p.location=f.get('location').trim();p.name=f.get('name').trim();p.number=f.get('number').trim();p.category=f.get('category').trim();p.equipmentGroups=f.getAll('equipmentGroups');p.supplier=f.get('supplier');p.aliases=f.get('aliases');if(!p.name)throw Error('Enter a part name');p.verified=p.quantity!==null&&!!p.location;if(p.quantity!==null&&!p.location)throw Error('Enter the current storage location to confirm this stock, or leave quantity blank for an uncounted part')});if(e.target.id==='service'){const hours=num(f,'hours'),used=num(f,'used'),date=f.get('date');if(!Number.isInteger(used))throw Error('Filters used must be a whole number');if(date>new Date().toISOString().slice(0,10))throw Error('Completion cannot be in the future');commit(s=>{if(hours<s.service.lastHours||date<s.service.lastDate)throw Error('Completion precedes the recorded baseline');if(used>0&&(s.parts[0].quantity===null||s.parts[0].quantity<used))throw Error('Confirm sufficient stock in Parts & Spares first');s.completions.push({id:crypto.randomUUID(),date,hours,used,notes:f.get('notes'),previous:structuredClone(s.service),reversed:false});if(used>0)s.parts[0].quantity-=used;s.service.lastHours=hours;s.service.lastDate=date})}if(e.target.id==='fuel'){const p={name:f.get('name'),start:num(f,'start'),end:num(f,'end'),added:num(f,'added'),distance:num(f,'distance'),duration:num(f,'duration')};p.litres=(p.start+p.added-p.end)*3.785411784;if(p.litres<0||p.distance<=0||p.duration<=0)throw Error('Check fuel amounts; distance and duration must be positive');commit(s=>s.passages.push(p))}if(e.target.id==='stock'){partSaved=true;if(e.submitter?.value!=='stay'&&e.target.dataset.saveMode!=='stay'){returnToParts();msg('Part saved on this device');return}}render();msg('Saved on this device')}catch(x){msg(x.message)}});
app.addEventListener('change',async e=>{try{if(e.target.dataset.check!==undefined){commit(s=>s.checks.at(-1).items[Number(e.target.dataset.check)].status=e.target.value);msg('Checklist saved')}if(e.target.id==='restore'&&e.target.files[0]){const next=JSON.parse(await e.target.files[0].text());validate(next);if(confirm('Replace current records? Export a backup first if needed.')){localStorage.setItem(KEY,JSON.stringify(migrate(next)));state=migrate(next);blocked=false;render();msg('Backup restored')}}}catch(x){msg(x.message)}});
function connection(){document.querySelector('#connection').textContent=navigator.onLine?'Online':'Offline'}window.addEventListener('online',connection);window.addEventListener('offline',connection);connection();render();
if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js').catch(()=>msg('Offline cache unavailable; keep a backup.'));

function nextDate(date,months){const [y,m,d]=date.split('-').map(Number);const dt=new Date(Date.UTC(y,m-1+months,1));dt.setUTCDate(Math.min(d,new Date(Date.UTC(dt.getUTCFullYear(),dt.getUTCMonth()+1,0)).getUTCDate()));return dt.toISOString().slice(0,10)}
function oldPartOptions(){return '<option value="">None</option>'+state.parts.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} · ${esc(p.number)}</option>`).join('')}
function optionalNum(f,k){return f.get(k)===''?null:num(f,k)}
app.addEventListener('input',e=>{if(e.target.id==='part-search'){const pos=e.target.selectionStart;search=e.target.value;render();const input=document.querySelector('#part-search');input.focus();input.setSelectionRange(pos,pos)}});
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;try{if(b.hasAttribute('data-partsback')){returnToParts();return}if(b.dataset.part){rememberPartsPosition();selectedPart=b.dataset.part;partSaved=false;page='part';render();window.scrollTo(0,0)}if(b.hasAttribute('data-newpart')){rememberPartsPosition();partSaved=false;const id=crypto.randomUUID();commit(s=>s.parts.push({id,name:'New part',number:'Unknown',category:'Other',quantity:null,location:'',minimum:1,supplier:'',aliases:'',verified:false}));selectedPart=id;page='part';render();window.scrollTo(0,0)}if(b.dataset.equipment){selectedTask=b.dataset.equipment;page='tasks';render()}if(b.dataset.task){selectedTask=b.dataset.task;page='task';render()}if(b.dataset.taskundo){commit(s=>{const c=s.completions.find(c=>c.id===b.dataset.taskundo);if(c.reversed||s.completions.filter(x=>x.taskID===c.taskID&&!x.reversed).at(-1)?.id!==c.id)throw Error('Undo the latest service for this task first');const t=s.tasks.find(t=>t.id===c.taskID);t.lastHours=c.previous.lastHours;t.lastDate=c.previous.lastDate;if(c.used>0)s.parts.find(p=>p.id===c.part).quantity+=c.used;c.reversed=true});render()}}catch(x){msg(x.message)}});
app.addEventListener('submit',e=>{const f=new FormData(e.target);try{if(e.target.id==='newtask'){const h=optionalNum(f,'intervalHours'),m=optionalNum(f,'intervalMonths');if((h!==null&&h<=0)||(m!==null&&(!Number.isInteger(m)||m<=0))||(!h&&!m))throw Error('Enter a positive hour or month interval');commit(s=>s.tasks.push({id:crypto.randomUUID(),equipment:selectedTask,name:f.get('name').trim(),source:f.get('source'),intervalHours:h,intervalMonths:m,lastHours:optionalNum(f,'lastHours'),lastDate:f.get('lastDate')||null,part:f.get('part')||null}));page='tasks';render();msg('Schedule saved')}if(e.target.id==='task-service'){const hours=optionalNum(f,'hours'),used=num(f,'used'),date=f.get('date');if(date>new Date().toISOString().slice(0,10))throw Error('Completion cannot be in the future');commit(s=>{const t=s.tasks.find(t=>t.id===selectedTask);if(t.intervalHours&&hours===null)throw Error('Enter hours for an hour-based schedule');if((hours!==null&&t.lastHours!==null&&hours<t.lastHours)||(t.lastDate&&date<t.lastDate))throw Error('Completion precedes the last service');const consumedPart=f.get('part')||null;const p=s.parts.find(p=>p.id===consumedPart);if(used>0&&(!p||!p.verified||p.quantity<used))throw Error('Confirm sufficient linked stock first');s.completions.push({id:crypto.randomUUID(),taskID:t.id,date,hours,used,part:consumedPart,notes:f.get('notes'),previous:{lastHours:t.lastHours,lastDate:t.lastDate},reversed:false});if(used>0)p.quantity-=used;if(hours!==null)t.lastHours=hours;t.lastDate=date});render();msg('Service saved')}}catch(x){msg(x.message)}});
app.addEventListener('change',async e=>{if(e.target.id!=='inventory-file'||!e.target.files[0])return;try{const imported=JSON.parse(await e.target.files[0].text());if(imported.format!=='suilven-inventory-1'||!Array.isArray(imported.parts)||imported.parts.length>5000)throw Error('Select the supplied inventory import file');for(const p of imported.parts)if(!p.id||typeof p.name!=='string'||typeof p.number!=='string')throw Error('Invalid inventory entry');let added=0;commit(s=>{for(const p of imported.parts){if(s.parts.some(x=>x.id===p.id))continue;const oil=s.parts.find(x=>x.id==='oil');if(p.number.replace(/\s/g,'')==='RE504836'&&oil){Object.assign(oil,{historicalQuantity:p.historicalQuantity,historicalLocation:p.historicalLocation,source:p.source,importID:p.id});continue}s.parts.push({...p,quantity:null,location:'',minimum:1,verified:false});added++}});page='parts';render();msg(`${added} entries imported locally. Historical locations and quantities need confirmation.`)}catch(x){msg(x.message)}});

function importSchedules(imported){if(imported.format!=='suilven-schedules-1'||!Array.isArray(imported.tasks)||imported.tasks.length>1000)throw Error('Select the supplied engine schedules JSON file');const ids=new Set();for(const t of imported.tasks){if(typeof t.id!=='string'||!t.id||ids.has(t.id)||!['Main engine','Wing engine','Generator','Other equipment'].includes(t.equipment)||typeof t.name!=='string'||typeof t.source!=='string')throw Error('Invalid schedule entry');ids.add(t.id);for(const key of ['intervalHours','intervalMonths','lastHours'])if(t[key]!==null&&(!Number.isFinite(t[key])||t[key]<0))throw Error('Invalid schedule number');if((t.intervalHours!==null&&t.intervalHours<=0)||(t.intervalMonths!==null&&(!Number.isInteger(t.intervalMonths)||t.intervalMonths<=0))||(!t.intervalHours&&!t.intervalMonths))throw Error('Invalid schedule interval');if(t.lastDate!==null&&!/^\d{4}-\d{2}-\d{2}$/.test(t.lastDate))throw Error('Invalid baseline date')}
let added=0;commit(s=>{for(const t of imported.tasks){if(s.scheduleDrafts.some(x=>x.id===t.id)||s.tasks.some(x=>x.importID===t.id))continue;s.scheduleDrafts.push({...t,activated:false});added++}});return added}
app.addEventListener('change',async e=>{if(e.target.id!=='schedule-file'||!e.target.files[0])return;try{const count=importSchedules(JSON.parse(await e.target.files[0].text()));render();msg(`${count} schedules imported for review. Existing records preserved.`)}catch(x){msg(x.message)}});
app.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.draft){selectedTask=b.dataset.draft;page='schedule-review';render()}});
app.addEventListener('submit',e=>{if(e.target.id!=='activate-schedule')return;e.preventDefault();try{const f=new FormData(e.target),h=optionalNum(f,'intervalHours'),m=optionalNum(f,'intervalMonths'),lh=optionalNum(f,'lastHours'),ld=f.get('lastDate')||null;if(!f.get('confirmed'))throw Error('Confirm the schedule checks first');if((h!==null&&h<=0)||(m!==null&&(!Number.isInteger(m)||m<=0))||(!h&&!m))throw Error('Enter a positive hour or month interval');if(ld&&ld>new Date().toISOString().slice(0,10))throw Error('Last service cannot be in the future');const basis=f.get('basis').trim();if(!basis)throw Error('Explain the chosen interval');let equipment;commit(s=>{const d=s.scheduleDrafts.find(d=>d.id===selectedTask);if(!d||d.activated)throw Error('Schedule already activated');equipment=d.equipment;s.tasks.push({id:crypto.randomUUID(),importID:d.id,equipment:d.equipment,name:d.name,source:d.source+' · Chosen basis: '+basis,reviewNotes:d.reviewNotes,intervalHours:h,intervalMonths:m,lastHours:lh,lastDate:ld,part:f.get('part')||null});d.activated=true});selectedTask=equipment;page='tasks';render();msg('Schedule activated on this device')}catch(x){msg(x.message)}});

const equipmentNames=['Main engine','Wing engine','Generator','Other equipment'];
function partGroups(p){if(Array.isArray(p.equipmentGroups))return p.equipmentGroups;const txt=[p.name,p.historicalLocation].join(' ').toLowerCase();const groups=[];if(p.id==='oil'||/\bmain\b|\bm\/e\b/.test(txt))groups.push('Main engine');if(/\bwing\b|\byanmar\b/.test(txt))groups.push('Wing engine');if(/\bgen\b|\bgenerator\b/.test(txt)||p.category==='Generator')groups.push('Generator');if(!groups.length&&p.category&& !['Engine','Generator','Filter','Drivetrain','Other'].includes(p.category))groups.push('Other equipment');return groups}
function filteredParts(equipment,query='',scope='equipment'){return state.parts.filter(p=>(scope==='all'||(scope==='unknown'?partGroups(p).length===0:partGroups(p).includes(equipment)))&&[p.name,p.number,p.aliases,p.supplier].join(' ').toLowerCase().includes(query.toLowerCase()))}
function optionLabel(p){return `${p.name} · ${p.number} · ${p.verified?p.quantity+' onboard':'stock unconfirmed'}${partGroups(p).length?'':' · equipment unassigned'}`}
function partOptions(equipment,query='',scope='all',selected=''){const parts=filteredParts(equipment,query,scope);const retained=state.parts.find(p=>p.id===selected);if(retained&&!parts.some(p=>p.id===selected))parts.unshift(retained);return '<option value="">None / no stock deduction</option>'+parts.map(p=>`<option value="${esc(p.id)}" ${p.id===selected?'selected':''}>${esc(optionLabel(p))}</option>`).join('')}
function partPicker(equipment,selected=''){return `<fieldset data-partpicker data-equipment="${esc(equipment)}"><legend>Service part · ${esc(equipment)}</legend><label>Show<select data-partscope><option value="equipment">${esc(equipment)} parts</option><option value="unknown">Unassigned equipment</option><option value="all">All stock / miscellaneous</option></select></label><label>Search part name or number<input data-partquery type="search" placeholder="e.g. belt or part number"></label><label>Select the part<select name="part">${partOptions(equipment,'','equipment',selected)}</select></label><p>Groups come from inventory descriptions, not verified fit. Edit a part to correct its equipment group. Shared parts can belong to several engines.</p></fieldset>`}
function refreshPartPicker(target){const box=target.closest('[data-partpicker]');if(!box)return;const select=box.querySelector('[name="part"]');select.innerHTML=partOptions(box.dataset.equipment,box.querySelector('[data-partquery]').value,box.querySelector('[data-partscope]').value,select.value)}
app.addEventListener('input',e=>{if(e.target.hasAttribute('data-partquery'))refreshPartPicker(e.target)});
app.addEventListener('change',e=>{if(e.target.hasAttribute('data-partscope'))refreshPartPicker(e.target)});

function rememberPartsPosition(){partsReturnPage=page==='reorder'?'reorder':'parts';partsScroll=page==='parts'||page==='reorder'?window.scrollY:0}
function returnToParts(){page=partsReturnPage;render();requestAnimationFrame(()=>window.scrollTo(0,partsScroll))}
app.addEventListener('input',e=>{if(e.target.closest?.('#stock')){partSaved=false;const notice=app.querySelector('.save-confirmation');if(notice)notice.remove()}});

app.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.form?.id==='stock')b.form.dataset.saveMode=b.value==='stay'?'stay':'return'});

let manualsDBPromise,manualImportBusy=false;
function manualsDB(){if(!manualsDBPromise)manualsDBPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('suilven-manuals',1);r.onupgradeneeded=()=>r.result.createObjectStore('pdfs',{keyPath:'id'});r.onsuccess=()=>{r.result.onversionchange=()=>{r.result.close();manualsDBPromise=null};resolve(r.result)};r.onerror=()=>{manualsDBPromise=null;reject(r.error)};r.onblocked=()=>{manualsDBPromise=null;reject(Error('Close other Suilven tabs and try again'))}});return manualsDBPromise}
async function manualStore(action,id,record){const db=await manualsDB();return new Promise((resolve,reject)=>{const tx=db.transaction('pdfs',action==='get'?'readonly':'readwrite'),store=tx.objectStore('pdfs');const r=action==='get'?store.get(id):action==='put'?store.put(record):store.delete(id);tx.oncomplete=()=>resolve(r.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('PDF storage aborted'))})}
function manualStatus(message){const el=document.querySelector('#manual-status');if(el)el.textContent=message;else msg(message)}
async function importManualFiles(files,equipment){if(blocked)throw Error('Restore readable records before importing manuals');let added=0;for(const file of files){if(!/\.pdf$/i.test(file.name))throw Error('Select PDF files only');const signature=new TextDecoder().decode(await file.slice(0,5).arrayBuffer());if(signature!=='%PDF-')throw Error(`${file.name} is not a readable PDF`);if(state.manuals.some(m=>m.name===file.name&&m.size===file.size&&m.modified===file.lastModified))continue;manualStatus(`Saving ${file.name} locally…`);const id=crypto.randomUUID(),meta={id,name:file.name,equipment:equipment==='Automatic from filename'?manualEquipment(file.name):equipment,size:file.size,modified:file.lastModified,imported:new Date().toISOString()};await manualStore('put',id,{id,blob:file});try{commit(s=>s.manuals.push(meta))}catch(e){await manualStore('delete',id);throw e}added++}return added}
app.addEventListener('submit',async e=>{if(e.target.id!=='manual-import')return;e.preventDefault();if(manualImportBusy)return;manualImportBusy=true;const button=e.target.querySelector('button');button.disabled=true;try{const files=Array.from(e.target.elements.files.files);if(!files.length)throw Error('Select a PDF from Files first');const added=await importManualFiles(files,e.target.elements.equipment.value);if(page==='manuals'){render();manualStatus(`✓ ${added} manual(s) saved locally. Repeated files skipped. Test opening one while offline.`)}}catch(x){manualStatus(`Import stopped: ${x.message}. Previously saved PDFs are retained.`)}finally{manualImportBusy=false;if(button.isConnected)button.disabled=false}});
app.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.manual){try{const m=state.manuals.find(m=>m.id===b.dataset.manual);manualStatus('Reading local PDF…');const record=await manualStore('get',m.id);if(!record?.blob)throw Error('PDF copy is missing from this browser. Re-import the original from Files; JSON restore does not restore PDFs.');const url=URL.createObjectURL(record.blob);const pdfPage=Number(b.dataset.pdfpage)||1;const pageURL=url+'#page='+pdfPage;const panel=document.createElement('section');panel.innerHTML=`<h2>${esc(m.name)}</h2><p>Reference: PDF page ${pdfPage}. Your iPad viewer may require you to enter that page manually.</p><a target="_blank" rel="noopener" href="${pageURL}">Open full PDF</a> · <a download="${esc(m.name)}" href="${url}">Save PDF to Files</a><button type="button">Close preview</button><iframe title="${esc(m.name)}" src="${pageURL}" style="width:100%;height:65vh;border:0"></iframe>`;panel.querySelector('button').onclick=()=>{panel.remove();URL.revokeObjectURL(url)};app.append(panel);panel.scrollIntoView({block:'start'});manualStatus('✓ Opened from local storage.')}catch(x){manualStatus(x.message)}}if(b.id==='manual-storage'){try{const estimate=await navigator.storage?.estimate?.();const retained=await navigator.storage?.persist?.();document.querySelector('#manual-storage-status').textContent=`${estimate?`Website storage: ${(estimate.usage/1048576).toFixed(1)} MB used; estimated allowance ${(estimate.quota/1073741824).toFixed(1)} GB. `:''}${retained?'Storage retention granted.':'Storage retention is not guaranteed.'} Keep original PDFs in Files.`}catch(x){manualStatus(x.message)}}});

function manualEquipment(name){if(/yanmar|3ym|km3v|km2p/i.test(name))return 'Wing engine';if(/l1066|lugger|john.?deere|1066t/i.test(name))return 'Main engine';if(/843nw|northern.?lights/i.test(name))return 'Generator';if(/maxwell|rocna|anchor/i.test(name))return 'Anchoring & Windlass';if(/trac|stabili/i.test(name))return 'Stabilisers';if(/water.?maker|wmkr|hro|ecosistem|cat pump/i.test(name))return 'Watermaker';if(/victron|multiplus|blue.?sea/i.test(name))return 'Electrical';if(/le[e]?ce|alternator/i.test(name))return 'Alternators';if(/tecma|sealand|toilet/i.test(name))return 'Sanitation';if(/racor/i.test(name))return 'Fuel filtration';if(/crane|davit|rib|tender/i.test(name))return 'Crane & tender';if(/yamaha/i.test(name))return 'Outboard';if(/dometic|air.?cond/i.test(name))return 'Air conditioning';if(/jabsco|shurflo|pump/i.test(name))return 'Pumps & plumbing';if(/n4334/i.test(name))return 'Boat handbook';return 'Other equipment — review grouping'}

function manualGroup(m){return m.groupOverride||(m.equipment&&!m.equipment.startsWith('Other equipment')?m.equipment:manualEquipment(m.name))}
function manualLibrary(){const groups=[...new Set(state.manuals.map(manualGroup))].sort();return `<label>Search saved manuals<input id="manual-search" type="search" placeholder="Name or equipment"></label><p>${state.manuals.length} local catalogue entries</p>${groups.map(g=>`<section data-manualgroup><h2>${esc(g)}</h2>${state.manuals.filter(m=>manualGroup(m)===g).map(m=>`<article data-manualentry data-search="${esc((m.name+' '+g).toLowerCase())}"><h3>${esc(m.name)}</h3><p>${((m.size??0)/1048576).toFixed(1)} MB</p><button data-manual="${esc(m.id)}">Open saved PDF</button><button data-groupmanual="${esc(m.id)}">Change equipment group</button></article>`).join('')}</section>`).join('')}`}
function referenceButton(m,page,label){return `<button type="button" data-manual="${esc(m.id)}" data-pdfpage="${page}">${esc(label)} · PDF page ${page}</button>`}
function serviceReferences(t){if(t.equipment==='Main engine'&&/oil|lube/i.test(t.name)&&!/gear/i.test(t.name))return mainOilReferences();let file='',pdf=1;const name=t.name.toLowerCase();if(t.equipment==='Main engine'){file='L1066T Op Manual 2010.pdf';pdf=/oil|air cleaner/.test(name)?15:/valve/.test(name)?16:/fuel filter|damper/.test(name)?17:/leak|turbo/.test(name)?25:13}else if(t.equipment==='Generator'){file='NL843NW2 Ops Manual 2009.pdf';pdf=/oil/.test(name)?12:/air|valve|belt/.test(name)?13:/fuel filter/.test(name)?14:/coolant|impeller|exchanger/.test(name)?18:10}else if(t.equipment==='Wing engine'){file='yanmar_ym_series_operations_manual_v2_21jan09.pdf';pdf=/oil|gear|fuel filter/.test(name)?57:/impeller|coolant|air|exhaust|water/.test(name)?58:59}
// Only oil/air and the visually checked schedule chart pages are direct references.
if(t.equipment==='Main engine'&&!/oil|air cleaner/.test(name))pdf=13;
if(t.equipment==='Generator'&&!/oil/.test(name))pdf=10;
const m=state.manuals.find(m=>m.name.toLowerCase()===file.toLowerCase());return `<section><h2>Manual reference</h2>${m?referenceButton(m,pdf,'Open task reference'):`<p>Matching reference PDF not found: ${esc(file||'No verified reference assigned')}.</p>`}<p>Check the fitted equipment and instructions. Schedule references do not confirm part compatibility.</p></section>`}
function partReferences(p){if(['RE504836','R502513'].includes((p.number||'').replace(/\s/g,'')))return mainOilReferences();const groups=partGroups(p),manuals=state.manuals.filter(m=>groups.includes(manualGroup(m)));return `<section><h2>Related equipment manuals</h2>${manuals.length?manuals.map(m=>referenceButton(m,1,m.name)).join(''):'<p>No matching equipment manual yet. Check the part’s equipment group.</p>'}<p>These are equipment references; this part number has not been verified against each manual.</p></section>`}
app.addEventListener('input',e=>{if(e.target.id==='manual-search'){const q=e.target.value.toLowerCase();for(const entry of app.querySelectorAll('[data-manualentry]'))entry.hidden=!entry.dataset.search.includes(q);for(const group of app.querySelectorAll('[data-manualgroup]'))group.hidden=!Array.from(group.querySelectorAll('[data-manualentry]')).some(x=>!x.hidden)}});
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b?.dataset.groupmanual)return;const m=state.manuals.find(m=>m.id===b.dataset.groupmanual);const box=document.createElement('section');box.innerHTML=`<h2>Group: ${esc(m.name)}</h2><form id="manual-group-edit" data-id="${esc(m.id)}"><label>Equipment group<input name="group" value="${esc(manualGroup(m))}" required></label><button>Save group</button></form>`;app.append(box);box.scrollIntoView({block:'start'})});
app.addEventListener('submit',e=>{if(e.target.id!=='manual-group-edit')return;e.preventDefault();try{const group=new FormData(e.target).get('group').trim();if(!group)throw Error('Enter equipment group');const id=e.target.dataset.id;commit(s=>s.manuals.find(m=>m.id===id).groupOverride=group);render();manualStatus('✓ Equipment group saved. PDF unchanged.')}catch(x){manualStatus(x.message)}});

function mainOilReferences(){const refs=[{name:'L1066T Op Manual 2010.pdf',page:15,label:'Oil / filter change instructions · SP2–SP3'},{name:'L1066T Parts Catalog 2016.pdf',page:35,label:'Exploded oil-filter assembly · 2016 catalogue'},{name:'L1066T Parts Manual 2018.pdf',page:35,label:'Exploded oil-filter assembly · 2018 catalogue'}];return `<section><h2>Oil & filter · instructions and diagrams</h2>${refs.map(r=>{const m=state.manuals.find(m=>m.name.toLowerCase()===r.name.toLowerCase());return m?referenceButton(m,r.page,r.label):`<p>${esc(r.label)}: matching local file not found (${esc(r.name)}).</p>`}).join('')}<p>Procedure: operating manual printed page 13, SP3. Diagram: parts catalogue printed page 1–29, oil filter item 19 (RE504836) and sealing ring item 20 (R502513).</p><p>The exploded view identifies assembly components, not a photographic service sequence. Check that the illustrated L1066T assembly matches your fitted engine before using it.</p></section>`}
